In [1]:
# http://www.hankcs.com/nlp/word2vec.html
# https://zhuanlan.zhihu.com/p/53425736 cbow 多个词加权后在做输出

In [2]:
import tensorflow as tf

In [3]:
text = "火星（Mars）是太阳系八大行星之一，是太阳系由内往外数的第四颗行星，属于类地行星，直径约为地球的53%，质量为地球的14%。自转轴倾角、自转周期均与地球相近，公转一周约为地球公转时间的两倍。橘红色外表是地表的赤铁矿（氧化铁）。我国古书上将火星称为“荧惑星”，西方古代（古罗马）称为“神话玛尔斯星”是十二星座白羊座的独一守护星，并非天蝎座的守护行星。火星基本上是沙漠行星，地表沙丘、砾石遍布且没有稳定的液态水体（2015年9月28日，美国宇航局公布火星上有少量的水。据法新社2018年7月25日报道，欧洲航天局(ESA)的研究员称，火星上发现了第一个液态地下水湖）。二氧化碳为主的大气既稀薄又寒冷，沙尘悬浮其中，每年常有尘暴发生。火星两极皆有水冰与干冰组成的极冠会随着季节消长。与地球相比，火星地质活动较不活跃，地表地貌大部分于远古较活跃的时期形成，有密布的陨石坑、火山与峡谷，包括太阳系最高的山：奥林帕斯山和最大的峡谷：水手号峡谷。另一个地形特征是南北半球的明显差别：南方是古老、充满陨石坑的高地，北方则是较年轻的平原。火星有两个天然卫星：火卫一和火卫二，形状不规则，可能是被隔离的矮小行星。在地球，火星肉眼可见，最高亮度可达-2.9等，八大行星中比木星、金星暗。2015年9月28日，美国航天局宣布火星存在流动水"

In [4]:
import jieba
word_list = jieba.cut(text, cut_all=False)
print("Default Mode: " + "/ ".join(word_list))  # 精确模式

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/ph/31crq1pj14n9pcl2xffj45j8t0c5l2/T/jieba.cache
Loading model cost 0.763 seconds.
Prefix dict has been built succesfully.


Default Mode: 火星/ （/ Mars/ ）/ 是/ 太阳系/ 八/ 大行星/ 之一/ ，/ 是/ 太阳系/ 由/ 内往/ 外数/ 的/ 第四颗/ 行星/ ，/ 属于/ 类地行星/ ，/ 直径约/ 为/ 地球/ 的/ 53%/ ，/ 质量/ 为/ 地球/ 的/ 14%/ 。/ 自转轴/ 倾角/ 、/ 自转/ 周期/ 均/ 与/ 地球/ 相近/ ，/ 公转/ 一周/ 约/ 为/ 地球/ 公转/ 时间/ 的/ 两倍/ 。/ 橘红色/ 外表/ 是/ 地表/ 的/ 赤铁矿/ （/ 氧化铁/ ）/ 。/ 我国/ 古书/ 上将/ 火星/ 称为/ “/ 荧惑/ 星/ ”/ ，/ 西方/ 古代/ （/ 古罗马/ ）/ 称为/ “/ 神话/ 玛尔斯/ 星/ ”/ 是/ 十二/ 星座/ 白羊座/ 的/ 独一/ 守护星/ ，/ 并非/ 天蝎座/ 的/ 守护/ 行星/ 。/ 火星/ 基本上/ 是/ 沙漠/ 行星/ ，/ 地表/ 沙丘/ 、/ 砾石/ 遍布/ 且/ 没有/ 稳定/ 的/ 液态水/ 体/ （/ 2015/ 年/ 9/ 月/ 28/ 日/ ，/ 美国宇航局/ 公布/ 火星/ 上/ 有/ 少量/ 的/ 水/ 。/ 据/ 法新社/ 2018/ 年/ 7/ 月/ 25/ 日/ 报道/ ，/ 欧洲航天局/ (/ ESA/ )/ 的/ 研究员/ 称/ ，/ 火星/ 上/ 发现/ 了/ 第一个/ 液态/ 地下水/ 湖/ ）/ 。/ 二氧化碳/ 为主/ 的/ 大气/ 既/ 稀薄/ 又/ 寒冷/ ，/ 沙尘/ 悬浮/ 其中/ ，/ 每年/ 常有/ 尘暴/ 发生/ 。/ 火星/ 两极/ 皆/ 有/ 水冰/ 与/ 干冰/ 组成/ 的/ 极冠/ 会/ 随着/ 季节/ 消长/ 。/ 与/ 地球/ 相比/ ，/ 火星/ 地质/ 活动/ 较/ 不/ 活跃/ ，/ 地表/ 地貌/ 大部分/ 于/ 远古/ 较/ 活跃/ 的/ 时期/ 形成/ ，/ 有/ 密布/ 的/ 陨石坑/ 、/ 火山/ 与/ 峡谷/ ，/ 包括/ 太阳系/ 最高/ 的/ 山/ ：/ 奥林帕斯/ 山/ 和/ 最大/ 的/ 峡谷/ ：/ 水手/ 号/ 峡谷/ 。/ 另/ 一个/ 地形/ 特征/ 是/ 南/ 北半球/ 的/ 明显/ 差别/ ：/ 南方/ 是/ 古老/ 、/ 充满/ 陨石坑/ 的/ 高地/ ，/ 北方/ 则/ 是/ 较/

In [5]:
char_list = list(text)
print(char_list)
char_num = len(set(char_list))

['火', '星', '（', 'M', 'a', 'r', 's', '）', '是', '太', '阳', '系', '八', '大', '行', '星', '之', '一', '，', '是', '太', '阳', '系', '由', '内', '往', '外', '数', '的', '第', '四', '颗', '行', '星', '，', '属', '于', '类', '地', '行', '星', '，', '直', '径', '约', '为', '地', '球', '的', '5', '3', '%', '，', '质', '量', '为', '地', '球', '的', '1', '4', '%', '。', '自', '转', '轴', '倾', '角', '、', '自', '转', '周', '期', '均', '与', '地', '球', '相', '近', '，', '公', '转', '一', '周', '约', '为', '地', '球', '公', '转', '时', '间', '的', '两', '倍', '。', '橘', '红', '色', '外', '表', '是', '地', '表', '的', '赤', '铁', '矿', '（', '氧', '化', '铁', '）', '。', '我', '国', '古', '书', '上', '将', '火', '星', '称', '为', '“', '荧', '惑', '星', '”', '，', '西', '方', '古', '代', '（', '古', '罗', '马', '）', '称', '为', '“', '神', '话', '玛', '尔', '斯', '星', '”', '是', '十', '二', '星', '座', '白', '羊', '座', '的', '独', '一', '守', '护', '星', '，', '并', '非', '天', '蝎', '座', '的', '守', '护', '行', '星', '。', '火', '星', '基', '本', '上', '是', '沙', '漠', '行', '星', '，', '地', '表', '沙', '丘', '、', '砾', '石', '遍', '布', '且', '没', '有', '稳', '定',

In [10]:
def get_window_sample(char_list, window_size):
    left_context = []
    right_context = []
    target = []
    for idx, item in enumerate(char_list):
        if idx+window_size+1 < len(char_list):
            print(char_list[idx:idx+window_size])
            left_context.append(''.join(char_list[idx:idx+window_size]))
            right_context.append(''.join(char_list[idx+window_size+1:idx+2*window_size+1]))
            target.append(char_list[idx+window_size])
    return left_context, right_context, target

In [11]:
left_context, right_context, target = get_window_sample(char_list, 4)

for item_left, item_right, item in zip(left_context[:3], right_context[:3], target[:3]):
    print(str(item_left) + "   ###   " + str(item) + "   ###   " + str(item_right) + '\n')

['火', '星', '（', 'M']
['星', '（', 'M', 'a']
['（', 'M', 'a', 'r']
['M', 'a', 'r', 's']
['a', 'r', 's', '）']
['r', 's', '）', '是']
['s', '）', '是', '太']
['）', '是', '太', '阳']
['是', '太', '阳', '系']
['太', '阳', '系', '八']
['阳', '系', '八', '大']
['系', '八', '大', '行']
['八', '大', '行', '星']
['大', '行', '星', '之']
['行', '星', '之', '一']
['星', '之', '一', '，']
['之', '一', '，', '是']
['一', '，', '是', '太']
['，', '是', '太', '阳']
['是', '太', '阳', '系']
['太', '阳', '系', '由']
['阳', '系', '由', '内']
['系', '由', '内', '往']
['由', '内', '往', '外']
['内', '往', '外', '数']
['往', '外', '数', '的']
['外', '数', '的', '第']
['数', '的', '第', '四']
['的', '第', '四', '颗']
['第', '四', '颗', '行']
['四', '颗', '行', '星']
['颗', '行', '星', '，']
['行', '星', '，', '属']
['星', '，', '属', '于']
['，', '属', '于', '类']
['属', '于', '类', '地']
['于', '类', '地', '行']
['类', '地', '行', '星']
['地', '行', '星', '，']
['行', '星', '，', '直']
['星', '，', '直', '径']
['，', '直', '径', '约']
['直', '径', '约', '为']
['径', '约', '为', '地']
['约', '为', '地', '球']
['为', '地', '球', '的']
['地', '球', '的', '5']
['球', '的', '5

In [7]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
# data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
# values = array(data)
# print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(char_list)
print(integer_encoded[:10])
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded[:10])
# invert first example
# inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])

[170 138 256  16  18  19  20 257 139  87]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [8]:
def CBOW(self):
    self.context = tf.placeholder(dtype=tf.float32, shape=[None, windows_size, vocab_size])
    self.left = tf.placeholder(dtype=tf.float32, shape=[None, windows_size, vocab_size])
    self.target = tf.placeholder(tf.float32, shape=[None, vocab_size])

    w_1 = tf.Variable(tf.random_uniform([vocab_size, embedding_dim], stddev=0.1))
    w_2 = tf.Variable(tf.random_uniform([embedding_dim, vocab_size], stddev=0.1))
                      
    left_encode = tf.matmul(left, w1)
    left_sum = tf.reduce_sum(left_encode, axis=1)
                      
    right_encode = tf.matmul(right, w1)
    right_sum = tf.reduce_sum(right_encode, axis=1)
    
    context_encode = tf.concat([left_encode, right_encode], 0)
    context_sum = tf.reduce_sum(context_encode, axis=1)
    
    outputs = tf.matmul(context_sum, w_2)
    loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits=outputs, labels=target)
    loss = tf.reduce_mean(loss)
    
    self.trainer = tf.train.AdamOptimizer(learning_rate=1e-3).minimize(loss)


In [9]:
import tensorflow as tf
import numpy as np

embedding_dim = 50
windows_size = 5
vocab_size = char_num

left_context, right_context, target = get_window_sample(integer_encoded, 4)

print(type(left_context))
left_context = np.asarray(left_context)
right_context = np.asarray(right_context)
target = np.asarray(target)
print(left_context[0:3])
print(right_context[0:3])
print(target[0:3])
# print(left_context[0:3])
# print(type(np.asarray(left_context)))
# print(left_context[0:3])

TypeError: sequence item 0: expected str instance, numpy.ndarray found

In [ ]:
# Dataset
data_loader = \
tf.data.Dataset.from_tensor_slices(
   {'left':left_context, 'right':right_context})  

# data_loader = \
# tf.data.Dataset.from_tensor_slices(
#     {'left':[[1],[2],[3]], 'right':[[4],[5],[6]], 'target':[[1],[2],[3]]})   


In [ ]:
#config = tf.ConfigProto()
iterator = data_loader.make_one_shot_iterator()
one_element = iterator.get_next()

sess = tf.Session()
model = CBOW()

while True:
    try:
        sample_batched = sess.run(one_element)
        left = sample_batched['left']
        right = sample_batched['right']
        target = sample_batched['target']
        
        outputs = sess.run(model.trainer,
                           feed_dict = {model.left:left,
                                        model.right:right,
                                        model.target:target})
    except tf.errors.OutOfRangeError:
        break